### PR TITLE
Restore original readme

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 should we move away from branding PiHome to run on raspberry pi? i was thinking more as LAMP stack or on any computer?

**Comment by twa127** [comment]
How about making it just Linux ?

**Comment by sandreialexandru** [comment]
Moving away from RPi would mean that no GPIO controller could be possible and a wireless boiler controller should be used.

**Comment by twa127** [comment]
Hi,

I've never run my live system on an RPi, it has always been a BeegleBone, I also have it running on 2 different versions of the OrangePi. This was the reason for using Adafruilt Blinka for the I/O, we can configure the system to run on anything which is supported by Blinka

**Comment by sandreialexandru** [comment]
Doesn't this mean that there should be some kind of automated GPIO pin mapping in the web UI?

**Comment by twa127** [comment]
Taken care of by gpio3_relay.py which detects the board and sets up the pin list accordingly

**Comment by sandreialexandru** [comment]
I've been going through the code and could not find any cut-off, based on boiler max time or zone max time? Did I miss something?
Also, when defining the minimum temperature for the slider, do you think that the value should be the actual set frost protection temperature + 1 ?

**Comment by twa127** [comment]
Hi,

You are correct not yet got around to live temp, I just put in what I'd been playing with, been in HVAC and porting to Orange Pi mode :-)

Your idea for min temp sounds good, I'll include

**Comment by sandreialexandru** [comment]
How would Raspberry Pi mode differ from Orange Pi? Is Orange Pi a better solution?

**Comment by twa127** [comment]
Hopefully there will be no difference except price/performance consideration, especially if going low cost with an RPi Zero

**Comment by twa127** [comment]
Another plus for an Orange Pi is that there are versions with onboard eMMC, so no need for microSD card

**Pull request merged**
