### PR TITLE
New MQTT Nodes

### PR DESCRIPTION
**Pull request by JSa1987**
New implementation of MQTT Nodes. All the code related to MQTT nodes is skipped if the MQTT nodes are not enabled.

### CODE REVIEW

**Comment by twa127** [comment]
Am I missing something, why is the same value being placed in 2 different variable and both passed to a function
gw3

**Comment by JSa1987** [comment]
@twa127 I'm not sure why when re-syncing the relays at the startup of the gateway.py script we are passing the Node ID as out_id (that is supposed to me the Message ID). This has always been there, I have not changed it. I guess this was because when pulling the relays status from the `relays` table there is no Message ID.

When the `set_relays()` function is called to change the status of a relay (line 503) the function is called correctly passing the Message ID as out_id and the Node ID ad out_node_id.

Maybe we can pass a NULL value when re-syncing the relays at startup and put an IF on lines 73, 96, 111 and 130 to skip the following code if out_id is NULL? 

```
        cur.execute(
            "UPDATE `messages_out` set sent=1 where id=%s", [out_id]
        )  # update DB so this message will not be processed in next loop
        con.commit()  # commit above
```

Something like `out_id = None` on line 382 and the following on lines 73, 96, 111 and 130:

```
        if out_id != None:
            cur.execute(
                "UPDATE `messages_out` set sent=1 where id=%s", [out_id]
            )  # update DB so this message will not be processed in next loop
            con.commit()  # commit above
```

If you agree with this approach I will make these changes, test it and re-submit the pull request.

**Comment by JSa1987** [comment]
Also line 395 should be `msg = str(out_node_id)  # Node ID`

**Comment by twa127** [comment]
I'm still confused I'm afraid, am I just not seeing this correctly, but to me lines 382 and 383 get the exactly the same table value and thus at line 408 parameter 3 and parameter contain exactly the same value

**Comment by JSa1987** [comment]
Yes, that is correct. The problem is that parameter 3 should be the ID of the record from the `message_out` table so that the the `set_relays()` function can set the "sent" flag for this record to 1. However, when calling the function on line 407 we are not sending a message from the the `message_out` table, but we are taking the relays current status from the `relays` table.
So there is nothing to be passed as parameter 3.

If you look at how the `set_relays()` function is called line 503 that is how the function is supposed to be used. This is why I'm suggesting to pass `None` as parameter 3 when calling the function on line 408 and then fix the `set_relays()` function skip the change of the sent flag in `messages_out` when the function is called with `out_id = None`.

**Comment by twa127** [comment]
I need to take a ore detailed look at your code, but first thought is why not construct out_id from somewhere, I'm just not sure me need the extra parameter out_node-id

I'll take a detailed look at your code, is the #225 version the one you want to deploy?

**Comment by JSa1987** [comment]
@twa127 when calling the function on line 408 there is no need of the Message ID, and we cannot reconstruct this as there is no message associated with this call of the function.

#225 this has this underlaying "issue" that has always been there in gateway.py. Let me try to fix it and I will send you a new version so you can have a good look at it.

**Comment by twa127** [comment]
@JSa1987 please be aware that although gateway.py was ported from PiHome, I wrote the relay handling routines in the MaxAir version and it currently works as I designed it to work. Rather than duplicate 99% of the code in set_relays() for use in the initial relay synchronization, I made set_relays() dual purpose. Hence your reference to an underlying issue may not actually be the case.

I still standby my comment that lines 382 and 383 make no sense at all, in this section of the code the 2 variables will always have the same value.

**Comment by twa127** [comment]
Perhaps and explanation of why the initial synchronization code was added in the first place:

- if the gateway stopped for any reason, then because controller.php was only sending an update message to the gateway on state change, then the relays would not have there previous state restored
- the  initial synchronization routine scans the relay table to fine all the relays installed
- it then tries to get the last message for each relay in turn
- if no record is found in messages_out, then that relay has not been allocated and does not require initialization and an empty message is passed to set_relays()
- 
- if a message_out record is found then that is passed to set_relays()

**Comment by JSa1987** [comment]
@twa127 ok, not I understand what you were trying to achieve. Now to make this working when scanning the `message_out` for the last message you should pull also the record ID, and this is what should be passed as out_id (while you were instead passing the Node ID as out_id). 

This is easy to fix we just need to pull also the ID when running the following query and pass this as out_id. Give me a couple of hours and I will integrate this in the latest version of gateway.py I have been working on.

`            cur.execute(
                "SELECT `sub_type`, `ack`, `type`, `payload` FROM `messages_out` where node_id = (%s) AND child_id = (%s) ORDER BY id DESC LIMIT 1",
                (out_node_id, out_child_id),
            )`

**Comment by JSa1987** [comment]
I will close this pull request and open a new one with the updated gateway.py.

**Comment by twa127** [comment]
okay that sounds a sensible way forward

**Comment by twa127** [comment]
can I suggest this as a replacement for the relay initialization code

[relay_init.txt](https://github.com/pihome-shc/PiHomeHVAC/files/7227886/relay_init.txt)

**Pull request closed without merging**
