### PR TITLE
Add Sensor Type GUI + Terminate gateway scrip if route to network gateway is lost

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 does this pull request include #100

**Comment by pihome-shc** [comment]
here is my output of db_update.php 
```
2021-04-29 23:54:22 - Applying Updates to Database.
MySQL Database Error with Query DROP TABLE `temperature_sensors`;
:Cannot delete or update a parent row: a foreign key constraint fails
MySQL Database Error with Query ALTER TABLE `zone_sensors` DROP `temperature_sensor_id`;
:Cannot drop index 'FK_zone_sensors_temperature_sensors': needed in a foreign key constraint
MySQL Database Error with Query ALTER TABLE `zone_sensors` DROP INDEX `FK_zone_sensors_temperature_sensors`;
:Cannot drop index 'FK_zone_sensors_temperature_sensors': needed in a foreign key constraint
```

**Comment by twa127** [comment]
Ah think I see the problem - you need to run migrate_sensors_relays.php not  db_update.php

**Comment by dvdcut** [comment]
something to note here: 
i was trying to restore my old database but i couldnt so i had to stop schedule service otherwise my pi just hung there. 

`systemctl stop pihome_jobs_schedule.service`

**Comment by twa127** [comment]
Hi,

Yes I found exactly the same issue, unfortunate new feature of scheduler.

**Comment by dvdcut** [comment]
may be best to stop service when running setup.php or update_db.php or setup_db.php and start service again once script finish

**Comment by twa127** [comment]
Good point, I'll look at including it it in the code

**Comment by twa127** [comment]
Actually giving it a bit more thought - I've not seen any problem when executing setup.php or update_db.php or setup_db.php, the only time I had a problem was when directly importing the whole database from the command line, where it hangs at the section where the jobs table is imported. @dvdcut have you had problems when running the php scripts?

**Pull request merged**
