### PR TITLE
Restore gateway.py

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@twa127 do we still need this restore if user install `pip3 install paho-mqtt python-etcd` we can make MQTT as separate service in parallel to gateway.py

**Comment by twa127** [comment]
My take on this:

1. we already have MQTT service defined in ajax.php, the new mqtt service should intergrade/replace this
2. from an efficiency stand point why over burden gateway.py with processing that is only relevant to installation who want to use MQTT
3. gateway.py is crucial to the operation of the system
4. we are having to install dependencies, which are only required for mqtt operation

My vote would be to restore gateway.py, users wanting to test mqtt could replace gateway.py with the  mqtt version. This mqtt feature should be a configurable service, with it's own backend processing.

**Comment by pihome-shc** [comment]
@twa127 well explained, 
@JSa1987 can you please move out the MQTT python related code from gateway.py to its own file and have it as separate services this way we can deal with dependencies through install.sh script if you need help with that let me know.

**Comment by JSa1987** [comment]
@twa127 Let me try to address your points:

1. We are still using the MQTT option in ajax.php to setup the MQTT connection (broker address, port, username, password etc.). So there is integration from the interface point of view. The previous attempt of implementing MQTT `/cron/mqtt.py` support was quite limited. This supports only SonoffTasmota temperature sensors and assumes that all messages published to the broker are from SonoffTasmota temperature sensors. This had no support for other type of MQTT temperature sensors and no support for MQTT relays. This is setup is still available, but in my opinion could be removed as it is replaced by the new implementation.
2. The installation of the `import paho.mqtt.client` is something that we need to find a way to handled. This same dependency is needed also my the current implementation of MQTT `/cron/mqtt.py` but there is no installation process that takes care of this dependency.
3. If the MQTT option is not used the additional processing `gateway.py` is already minimal, and I can further reduce this to evaluating just a if condition to check if the MQTT option is enabled and if this is not the case skip everything related to MQTT.
4. I completely agree that `gateway.py` is critical to operation of the system. My initial plan was to implement MQTT as a stand alone script. I came to the conclusion that while this can be easily done for MQTT sensors to have a reliable solution for MQTT relays this should be in `gateway.py`. The same way `gateway.py` processes GPIO, MySensors and Tasmota relays. These are not relevant to all users but to have a reliable solution we have all these in `gateway.py`, and the additional processing involved is minimal.
5. I can have `gateway.py` load the additional dependency only the MQTT option is enabled. This will avoid having users that do not use it have to install and load the dependency.

I think that if we want a reliable MQTT solution for relays this needs to be in `gateway.py` as we have for GPIO, MySensors and Tasmota relays. We do not have separate scripts for GPIO, MySensor and Tasmota even though most users do not actually use all of them.
I think having a good stable solution to handle MQTT "relays" is really important as in a boiler system this will allow us to control [smart TRVs](https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html) to control the radiators one by one or in an HVAC system to control `smart vents` to control airflow in each room!
The concern raised are very valid. I think that work can be done to clean up the code to avoid any additional processing if the MQTT option is not in use, and avoid having to install and load the dependency. We can aim at having the changes completely skipped in case the MQTT option is not enabled.

@twa127  / @pihome-shc 
I will work cleaning up the code to achieve this and I will send you a new version so that we can review it and discuss it before merging it in the main branch.

**Pull request merged**
