### PR TITLE
Use of column description instead of fix index to access the cursor

### PR DESCRIPTION
**Pull request by JSa1987**
Hello,

As suggested by @twa127 for another python script I updated all the MQTT code in gateway.py to use the column description to access the cursor instead for direct indexes. This way if any changes to the database structure are made in the future this will not require adjusting the code.

### CODE REVIEW

**Comment by JSa1987** [comment]
Changed the database structure to use the id from nodes instead of nodes_id. As suggested by @twa127.
Cleaned up the code with python black.

**Comment by JSa1987** [comment]
I removed "" from lines 219, 245, 262, 277 and 293 to be compatible with the new database structure.

**Comment by pihome-shc** [comment]
@JSa1987 is this pull request ready for merge ?

**Comment by JSa1987** [comment]
Yes, this is ready to be merged. Thank you!

**Pull request merged**
