### PR TITLE
HA Integration

### PR DESCRIPTION
**Pull request by JSa1987**
Integration to monitor and control MaxAir from Home Assistant via MQTT.

### CODE REVIEW

**Comment by pihome-shc** [comment]
#78

**Comment by twa127** [comment]
Hi,

Could you please create the sql update file to add any changes to the mqtt table, the naming format is ddmmyy.sql and the file sits in MySQL_Database/database_updates/ that way it should get deployed automatically

**Comment by JSa1987** [comment]
@pihome-shc this implementation supersedes of what was discussed in #78. The integration is now achieved over MQTT instead of webhooks. This allows way more functionalities to be implemented and no configuration at all needed from Home Assistant side. What is described on the `[article on pihome](https://www.pihome.eu/2021/03/27/integrated-home-assistant-with-pihome/)` is not needed anymore, so that could probably be removed. The only steps needed for installation and setup is what is mentioned in the readme.md.

@twa127 thank you for mentioning this, it made me realize that I had not updated the readme.md to reflect what is needed with the final implementation. No changes are needed to the database (i.e. to the mqtt table). I have now pushed a revised version of the readme.md file.
The only change made to other parts of the system is a small change to the ajax.php to include the "Home Assistant Integration" option in the Type drop down menu for MQTT connections.

**Comment by twa127** [comment]
@JSa1987 looks good, if you get the time perhaps you could knock-up some documentation, every bit helps.

**Comment by JSa1987** [comment]
Yes, I will create a .docx and .pdf for this. It shouldn't take too long.

**Comment by twa127** [comment]
@JSa1987 thanks I'll integrate with the rest of the documentation once your done, perhaps we should call it a Knowledge Base rather than Documentation

**Comment by JSa1987** [comment]
@twa127 / @pihome-shc / @dvdcut I'm looking at adding support also for temperature sensors that are not linked to any zone as @scottagecheeseandcrackers mentioned in #78 .

The values for the sensors that are not linked to a zone need to be pulled from the `messages_in `table, right? 
I tried to add a sensor without zone and I noticed in the `sensors `table the zone_id was set to 0. Is this always the case?
If so, I was thinking looking in the `sensors` table for the sensor with `zone_id=0` and then look into the `messages_in` table for the last value from those sensor... will this prevent pulling the values from the sensors linked to a zone?
For the zones I already pull the current temperature from the `zone_current_state `table.

**Comment by twa127** [comment]
All sensors not allocated to a zone have zone_id = 0, you would need to find the node_id for the sensor to get its temp from the messages in table

**Comment by twa127** [comment]
I'm afraid that this deployment does not meet the core requirements for MaxAir.

MaxAir is specified to be installable on a range of SBC, the current version of the HomeAssistant service is Raspberry Pi specific and until it is made cross platform compliant, in my opinion, should be removed from the Add-On section of this project.

**Comment by JSa1987** [comment]
Fair point. I see three ways around this:

1. Remove the support for Power Supply issue detection on Raspberry Pi
2. Add the Power Supply issue detection functionality for all SBC supported
3. Enable the Power Supply issue detection only when a Raspberry Pi is used

To explore option number 2 @twa127 could you please give the list of all SBCs currently supported?

**Comment by JSa1987** [comment]
Seems that option number 2 is not possible as not all SBC have the hardware to check the status of the power supply. I will then go for option number 3.

I'm planning to change install.sh as follow:

```
MODEL=$( cat /proc/device-tree/model  )
if [[ $MODEL == *"Raspberry"* ]]; then
  echo "Model: Raspberry"
  REQUIREMENTS=requirements_RPi.txt
else
  echo "Model: generic SBC"
  REQUIREMENTS=requirements.txt
fi
```

and HA_HVAC_integration as follow:

```
try:
    from rpi_bad_power import new_under_voltage
    CHECK_RPI_POWER = True
except ImportError:
    CHECK_RPI_POWER = False
```

Any concerns with this solution?

**Comment by twa127** [comment]
full list of tested compliant SBCs is at https://github.com/pihome-shc/PiHomeHVAC, the non RPi boards are all running Armbian OS (Debian Buster)

the above fix works for me, also psutil and pytz are not installed by default in Armbian

**Comment by twa127** [comment]
the code at line 83 may cause an issue for zones with no sensor attached

cur.execute('SELECT `frost_temp` FROM `sensors` WHERE `sensor_id` = (%s)', [row[1]])

can I also suggest you don't use row[x] but index the cursor, otherwise possible future table changes will break the code

**Comment by twa127** [comment]
tested a bit more the issue is down to the fact that the python modules do not load because the python header files are missing, if installed using sudo apt-get install python3-dev then the install.sh will run okay and Armbian can cope with running new_under_voltage()

**Comment by twa127** [comment]
sorry another suggestion, unless I missed it there is no mention of installing mosquitto

**Comment by JSa1987** [comment]
@twa127 for the Home Assistant integration Home Assistant would be running the mosquito broker. MaxAir will just be the client. So no need to instal mosquito on Home Assistant.

**Comment by twa127** [comment]
okay does that mean that I need to install Home Assistant as a prerequisite ?

**Comment by twa127** [comment]
please bear with me, I've not looked at either Home Assistant or MQTT before now

**Comment by JSa1987** [comment]
@twa127 The Home Assistant integration is targeted to users that use both MaxAir and Home Assistant. This allows them to monitor and control MaxAir from Home Assistant and the Home Assistant app for smartphones.
Communication between MaxAir and Home Assistant uses the MQTT protocol (but this has nothing to do with MaxAir support for MQTT nodes). Home Assistant runs its Mosquito broker and the integration connects to this.

For the overall system the user can change the MaxAir mode (OFF, Timer, CE, HW etc.) and trigger the away mode.

For stand alone MaxAir sensors the user can monitor the sensor value, last seen time and date and in case the sensor is a MySensor the battery voltage and percentage.

For the MaxAir zones the user can see from Home Assistant the current temperature, target temperature last seen time and date and in case the sensor is a MySensor the battery voltage and percentage. In addition, the user can activate the boost function for the zone and the adjust the live temperature.

**Comment by pihome-shc** [comment]
guys can we move conversation to https://github.com/pihome-shc/PiHomeHVAC/issues/78

**Comment by JSa1987** [comment]
@pihome-shc #78 was my first attempt to implement an Home Assistant integration, that was based on webhooks. It supported a limited number of functionalities and require a massive amount of manual configuration on the Home Assistant side.
#201 achieves the integration via the MQTT protocol, supports pretty much all MaxAir functionalities and is plug and play on on Home Assistant side (no configuration needed).

**Comment by JSa1987** [comment]
@twa127 how do you want to handle the rpi_bad_power dependency for the Home Assistant integration?

As of now I have the install script to install this dependency only on Raspberry Pi and to install the python3-dev if not installed:
```
MODEL=$(tr -d '\0' </proc/device-tree/model)
if [[ $MODEL == *"Raspberry"* ]]; then
  echo "Model: Raspberry"
  REQUIREMENTS=requirements_RPi.txt
else
  echo "Model: generic SBC"
  REQUIREMENTS=requirements.txt
fi

PYTHON3DEV=$( apt-cache pkgnames python3-dev )
if [[ $PYTHON3DEV == *"python3-dev"* ]]; then
  echo "Python3-dev is already installed"
else
  echo "Installing Python3-dev"
  apt-get install -y python3-dev
fi

echo "Installing Phyton modules"
pip3 install -r $REQUIREMENTS
```
[requirements_RPi.txt](https://github.com/pihome-shc/PiHomeHVAC/files/7274478/requirements_RPi.txt)
[requirements.txt](https://github.com/pihome-shc/PiHomeHVAC/files/7274479/requirements.txt)

And I have the python script setup to try to load the rpi_bad_power dependency and if this fails to disable the part of the script that uses new_under_voltage() . In addition, also if new_under_voltage() returns `None` the part of the script that uses this function is disabled.

```
try:
    from rpi_bad_power import new_under_voltage
    CHECK_RPI_POWER = True
except ImportError:
    CHECK_RPI_POWER = False
if new_under_voltage() is None:
    CHECK_RPI_POWER = False
```

Are you happy with this setup?

**Pull request merged**
