### PR TITLE
Bug Fix for schedulelist.php to display status icons correctly + controller.php add missing variable initialization

### PR DESCRIPTION
**Pull request by twa127**

### CODE REVIEW

**Comment by pihome-shc** [comment]
@JSa1987 can you please review this change ?

**Comment by twa127** [comment]
@JSa1987 only change to #112 

try:
    import paho.mqtt.client as mqtt
except ModuleNotFoundError:
    # Error handling
    pass

and removal of confusing print statement

**Comment by JSa1987** [comment]
@twa127 / @pihome-shc please hold off in merging the gateway.py file.
I have made similar changes (and a couple more optimization to the MQTT part) and have been testing this for the last couple of days. Now it really skips everything MQTT related if the option is not enabled.

I will submit a pull request for gateway.py.

The other changes made to controller.php and schedulelist.php look good from my side.

**Comment by twa127** [comment]
@JSa1987 the gateway is already in this pull request

**Comment by twa127** [comment]
your #225 un-does the fix I put in #224

**Comment by JSa1987** [comment]
@twa127 could you please elaborate on the fix you put in #224 that was un-done?

With the version of gateway.py included in #224 some parts of the MQTT code is still executed even if the MQTT option is disabled. Part of this is opening an additional connection to the database that not needed if MQTT nodes are not used and this will unnecessary slow down performances for users that will not use MQTT. In #225 none of the MQTT code is executed in case the MQTT option is not enabled.

**Comment by twa127** [comment]
take the gateway change out

**Comment by JSa1987** [comment]
Yes, that is best. Once I have this out_id thing figure out I will push a new gateway.py

**Comment by pihome-shc** [comment]
@JSa1987 & @twa127 are we in agreement for this pull request to be merged ?

**Comment by JSa1987** [comment]
@pihome-shc yes, we can merge the latest version of this pull request where @twa127 removed the change from gateway.py

**Comment by JSa1987** [comment]
@pihome-shc I submitted #226 with the new gateway.py. Let's wait for @twa127 to review that before merging it into the main.

**Pull request merged**
